blog/urls.py
from django.urls import path
from .views import post_list, post_detail, post_share



urlpatterns = [
    path('', post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<post>/', post_detail, name='post_detail'),
    path('<post_id>/share/', post_share, name='post_share')
]

myBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class Post(models.Model):
    STATUS_CHOICE = {
        ('draft', 'Draft'),
        ('published', "Published"),
    }
    title = models.CharField(max_length=180)
    slug = models.SlugField(max_length=180, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateField(default=timezone.now)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICE,
                              default='draft')

    objects = models.Manager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return "%s by %s" % (self.title, self.author)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE ,related_name='comments')
    name = models.CharField(max_length=40)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment add by {} for {}'.format(self.name, self.post)


blog/forms.py
from django import forms
from .models import Comment


class Email(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from .forms import Email, CommentForm
from django.core.mail import send_mail


# Create your views here.

def post_list(request):
    posts = Post.objects.filter(status="published")
    paginator = Paginator(posts, 2)
    page = request.GET.get('page')
    try:
        listed_posts = paginator.page(page)
    except PageNotAnInteger:
        listed_posts = paginator.page(1)
    except EmptyPage:
        listed_posts = paginator.page(paginator.num_pages)

    context = {
        'posts': listed_posts,
    }
    return render(request, 'post/list.html', context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             )
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    context = {
        'post': post,
        'year': year,
        'month': month,
        'day': day,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'post/detail.html', context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = Email(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} send ({}) from: {} '.format(cd['name'], cd['email'], post.title)
            message = 'Read post "{}" on the site{}\n\nComment add by {}:{}'.format(post.title, post_url,
                                                                                    cd['name'], cd['comments'])
            send_mail(subject, message, 'mik4llpl@gmail.com', [cd['to']])
            sent = True
    else:
        form = Email()

    context = {
        'post': post,
        'form': form,
        'sent': sent,
    }
    return render(request, 'post/share.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

<div id="content">
    {% block body %}


    {% endblock %}
</div>
<nav>
    <h2>Weremiko blog</h2>
    <p>This is my blog :)</p>
</nav>
</body>

</html>

templates/paginator.html
<div id="paginator">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page: {{page.number}} from {{page.paginator.num_page}}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

templates/post/detail.html
{% extends 'base.html' %}
{% block title %}{{post.title}}{% endblock %}
{%block body %}
<h1>{{post.title}}</h1>
<p>
<div id="date">Published {{post.publish}} by {{post.author}}</div>
</p>
{{post.body|linebreaks}}
<p>
    <a href="{% url 'blog:post_share' post.id %}">
        Share Post
    </a>
</p>
{% with comments.count as total_comments %}
<h2>
    {{total_comments}} comment{{total_comments|pluralize:'s'}}
</h2>
{% endwith%}
{% for comment in comments %}
<div class="comments">
    <p class="info">
        comment {{forloop.counter}} add by {{comment.name}}
        {{comment.created}}

    </p>
    {{comment.body}}
</div>
{% empty %}
<p>No comments</p>
{% endfor %}
{% if new_comment %}
<h2>Your comment was added</h2>
{% else %}
<h2>add new comment</h2>
<form action="." method="post">
    {{comment_form.as_p}}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"> </p>
</form>
{% endif %}
{% endblock %}

templates/post/list.html
{% extends 'base.html' %}
{% block title%} blog {% endblock %}
{% block body %}
<h1>My blog</h1>
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{post.title}}
    </a>
</h2>
<p>
<div id="date">Published |{{post.publish}}| by {{post.author}}</div>
</p>
{{post.body|truncatewords:30|linebreaks}}
{% endfor %}
{% include "paginator.html" with page=posts %}
{% endblock%}

templates/post/share.html
{% extends 'base.html' %}
{% block title %}Share Post{% endblock %}
{% block body %}
{% if sent %}
    <h1>Email message has been sent</h1>
    <p>
        Sending post "{{post.title}}" to {{cd.to}} was successful!
    </p>
{% else %}
    <h1>Share "{{post.title}}" via e-mail!</h1>
    <form action="." method="post">

        {% csrf_token %}
        <div id="form-group">
                {{form.as_p}}
            </div>
        <input type="submit" value="Send e-mail message ">
    </form>
{% endif%}
{% endblock %}